version: "3.3"

services:
  # MySQL
  mysql:
    container_name: "mysql_v3"
    build: ./mysql
    restart: always
    tty: true
    environment:
      - MYSQL_USERNAME=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./log/mysql:/var/log/mysql 
    networks:
      - local-net

  # FastAPI
  backend:
    links:
      - mysql
    container_name: "backend_v3"
    build: ./backend
    environment:
      - MYSQL_USERNAME=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - BACKEND_URL=${BACKEND_URL}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/backend
    networks:
      - local-net

  # Frontend
  frontend:
    container_name: "frontend_v3"
    build: ./frontend
    volumes:
      - './frontend:/app'
    ports:
      - "80:80"
    networks:
      - local-net


  # PhpMyAdmin
  phpmyadmin:
    build: ./phpmyadmin
    container_name: "phpmyadmin_v3"
    environment:
      - PMA_ARBITRARY=1
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD= ${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD= ${MYSQL_ROOT_PASSWORD}
#      - MAX_EXECUTION_TIME= ${MAX_EXECUTION_TIME}
#      - MEMORY_LIMIT= ${MEMORY_LIMIT}
#      - UPLOAD_LIMIT= ${UPLOAD_LIMIT}
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - local-net


networks:
  local-net:
    driver: bridge
